const supportLanguage = [
    // {name:'아프리칸스어', 	code:'af'},
    // {name:'알바니아어', 	code:'sq'},
    // {name:'암하라어', 	code:'am'},
    // {name:'아랍어', 	code:'ar'},
    // {name:'아제르바이잔어', 	code:'az'},
    // {name:'벵골어', 	code:'bn'},
    // {name:'보스니아어', 	code:'bs'},
    // {name:'불가리아어', 	code:'bg'},
    // {name:'카탈란', 	code:'ca'},
    {name:'중국어 간체', 	code:'zh'},
    {name:'중국어 번체', 	code:'zh-TW'},
    // {name:'크로아티아어', 	code:'hr'},
    // {name:'체코어', 	code:'cs'},
    // {name:'덴마크어', 	code:'da'},
    // {name:'다리어', 	code:'fa-AF'},
    // {name:'네덜란드어', 	code:'nl'},
    {name:'영어', 	code:'en'},
    // {name:'에스토니아어', 	code:'et'},
    // {name:'페르시아어', 	code:'fa'},
    // {name:'핀란드어', 	code:'fi'},
    {name:'프랑스어', 	code:'fr'},
    // {name:'프랑스어(캐나다)', 	code:'fr-CA'},
    // {name:'그루지야어', 	code:'ka'},
    {name:'독일어', 	code:'de'},
    {name:'그리스어', 	code:'el'},
    // {name:'구자라티', 	code:'gu'},
    // {name:'아이티어', 	code:'ht'},
    // {name:'하우사어', 	code:'ha'},
    // {name:'히브리어', 	code:'he'},
    // {name:'힌디어', 	code:'hi'},
    // {name:'헝가리어', 	code:'hu'},
    // {name:'인도네시아어', 	code:'id'},
    {name:'이탈리아어', 	code:'it'},
    {name:'일본어', 	code:'ja'},
    // {name:'카타나다', 	code:'kn'},
    // {name:'카자키', 	code:'kk'},
    {name:'한국어', 	code:'ko'},
    // {name:'라트비아어', 	code:'lv'},
    // {name:'리투아니아어', 	code:'lt'},
    // {name:'마케도니아어', 	code:'mk'},
    // {name:'말레이어', 	code:'ms'},
    // {name:'말레이어', 	code:'ml'},
    // {name:'몰트', 	code:'mt'},
    // {name:'몽골어', 	code:'mn'},
    // {name:'페르시아어', 	code:'fa'},
    // {name:'파슈토어', 	code:'ps'},
    {name:'폴란드어', 	code:'pl'},
    {name:'포르투갈어', 	code:'pt'},
    // {name:'루마니아어', 	code:'ro'},
    {name:'러시아어', 	code:'ru'},
    // {name:'세르비아어', 	code:'sr'},
    // {name:'슬로바키아어', 	code:'sk'},
    // {name:'슬로베니아어', 	code:'sl'},
    // {name:'소말리아어', 	code:'so'},
    {name:'스페인어', 	code:'es'},
    // {name:'스페인어(멕시코)', 	code:'es-MX'},
    // {name:'스와힐리어', 	code:'sw'},
    {name:'스웨덴어', 	code:'sv'},
    // {name:'타갈로그어', 	code:'tl'},
    // {name:'타밀어', 	code:'ta'},
    {name:'태국어', 	code:'th'},
    // {name:'터키어', 	code:'tr'},
    // {name:'우크라이나어', 	code:'uk'},
    // {name:'우르두어', 	code:'ur'},
    {name:'베트남어', 	code:'vi'},
    // {name:'웨일스어', 	code:'cy'}
];

export default supportLanguage;
