const supportLanguage = [
    // {name:'걸프 아랍어', code:'ar-AE'},
    // {name:'현대 표준 아랍어', code:'ar-SA'},
    {name:'표준 중국어 - VPN', code:'zh-CN'},
    // {name:'네덜란드어', code:'nl-NL'},
    {name:'호주 영어', code:'en-AU'},
    {name:'영국 영어', code:'en-GB'},
    {name:'인도 영어', code:'en-IN'},
    // {name:'아일랜드 영어', code:'en-IE'},
    // {name:'스코틀랜드 영어', code:'en-AB'},
    {name:'미국 영어', code:'en-US'},
    // {name:'웨일스 영어', code:'en-WL'},
    {name:'스페인어', code:'es-ES'},
    // {name:'미국 스페인어', code:'es-US'},
    {name:'프랑스어', code:'fr-FR'},
    // {name:'캐나다 프랑스어', code:'fr-CA'},
    // {name:'페르시아어', code:'fa-IR'},
    {name:'독일어', code:'de-DE'},
    // {name:'스위스 독일어', code:'de-CH'},
    // {name:'히브리어', code:'he-IL'},
    // {name:'인도 힌디어', code:'hi-IN'},
    // {name:'인도네시아어', code:'id-ID'},
    {name:'이탈리아어', code:'it-IT'},
    {name:'일본어', code:'ja-JP'},
    {name:'한국어', code:'ko-KR'},
    // {name:'말레이어', code:'ms-MY'},
    {name:'포르투갈어', code:'pt-PT'},
    // {name:'브라질 포르투갈어', code:'pt-BR'},
    {name:'러시아어', code:'ru-RU'},
    // {name:'타밀어', code:'ta-IN'},
    // {name:'텔루구어', code:'te-IN'},
    // {name:'터키어', code:'tr-TR'}
];

export default supportLanguage;